### ISSUE TITLE
Test packages for the next fedora release

### ISSUE THREAD

**Issue by 1dot75cm** [FZUG/deepin-desktop#1]
Step 1: make sure your system is Fedora 29
Step 2: install the `fedora-repos-rawhide` package and choose the better speed mirror site ([https://mirrors.kernel.org](https://ewr.edge.kernel.org/fedora-buffet/fedora/linux/))
Step 3: enter the following command
```
# dnf install deepin-desktop
```
Step 4: reboot, and select the `deepin` item in GDM
Step 5: test and feedback on each of your problems
@FZUG/tier2 @sztsian

**Comment by alick** [comment]
Hi, now that the deepin packages are already in the official Fedora repo, I feel it is time to use the official channel for announcements etc. For example, we can ask the community to help test by posting to https://communityblog.fedoraproject.org/

Of course, we can post another one in Chinese to https://zh.fedoracommunity.org

**Comment by sztsian** [comment]
I agree, but let's wait for some soak time. All the package are just finished yesterday so I believe many of the tier 2 Fedora repos are not up-to-date yet. So I will possible send out the `Self Contained Changes` along with the test announcement within this month.

**Comment by y010204025** [comment]
额，我还是使用中文回复吧。
我先启用了deepin的copr:
sudo dnf copr enable mosquito/deepin
然后执行：
sudo dnf install deepin-desktop
提示安装的软件包如下：
<pre>================================================================================
 软件包                 架构   版本                       仓库             大小
================================================================================
安装:
 deepin-desktop         x86_64 4.7.1.1-1.fc29             mosquito-deepin 1.9 M
安装依赖关系:
 deepin-file-manager    x86_64 4.7.1.1-1.fc29             mosquito-deepin 3.0 M
 deepin-menu            x86_64 3.4.0-1.fc29               mosquito-deepin  59 k
 deepin-qt-dbus-factory x86_64 1.0.5-1.fc29               mosquito-deepin 504 k
 deepin-terminal        x86_64 3.0.10.2-1.fc29            mosquito-deepin 245 k
 deepin-terminal-data   noarch 3.0.10.2-1.fc29            mosquito-deepin 189 k
 dtkcore                x86_64 2.0.9.8-1.fc29             mosquito-deepin 278 k
 dtkwidget              x86_64 2.0.9.9-1.fc29             mosquito-deepin 694 k
 deepin-shortcut-viewer x86_64 1.3.4-2.fc29               fedora           49 k
 expect                 x86_64 5.45.4-5.fc29              fedora          251 k
 gsettings-qt           x86_64 0-0.16.20180723bzr85.fc29  fedora           41 k
 jemalloc               x86_64 5.1.0-2.fc29               fedora          207 k
安装弱的依赖:
 zssh                   x86_64 1.5c-1.fc29                mosquito-deepin  32 k
跳过存在损坏依赖关系的软件包 :
 deepin-daemon          x86_64 3.2.9-2.fc29               fedora           22 M
 deepin-daemon          x86_64 3.7.0-1.fc29               mosquito-deepin  25 M
 deepin-desktop         x86_64 4.7.1.1-2.fc29             mosquito-deepin 1.9 M
 deepin-polkit-agent    x86_64 0.1.1-3.fc29               fedora           66 k
 deepin-session-ui      x86_64 4.2.0-3.fc29               fedora          2.6 M
 deepin-session-ui      x86_64 4.6.2-1.fc29               mosquito-deepin 2.8 M

事务概要
================================================================================
安装  13 软件包
跳过   6 软件包

总下载：7.4 M
安装大小：26 M
确定吗？[y/N]： </pre>
选择Y继续安装，安装成功后注销，GDM并没有deepin的选项，是我的依赖有问题么，我的f29是从f28升级上来的。

**Comment by sztsian** [comment]
Deepin DE 暂时只在 Rawhide 里完成更新了。 我们会在 Rawhide 中测试之后再考虑推送到 Fedora 29

**Comment by y010204025** [comment]
> Deepin DE 暂时只在 Rawhide 里完成更新了。 我们会在 Rawhide 中测试之后再考虑推送到 Fedora 29

OK，明白了，辛苦了。不知会不会添加 netease-cloud-music，deb安装起来很麻烦。

**Comment by sztsian** [comment]
网易云音乐没有开源。不会出现在任何 Fedora 相关软件仓库。

**Comment by y010204025** [comment]
> 网易云音乐没有开源。不会出现在任何 Fedora 相关软件仓库。

OK,明白

**Comment by shrisha108** [comment]
Trying to install on Fedora 29 and getting error : Problem: conflicting requests
  - nothing provides libdframeworkdbus.so.1()(64bit) needed by deepin-desktop-4.4.7-9.fc29.x86_64
So I installed deepin-qt-dbus-factory package which provides libdframeworkdbus.so.2 and made symlink to libdframeworkdbus.so.1 But still getting same error. Anyone can help with this? Thank you.

**Comment by 1dot75cm** [comment]
@shrishadas
You need to check the `fedora-rawhide.repo` config file and turn on the `[rawhide]` repository. And then, you'd better modify the `baseurl` option. The following is for your reference.

```
[rawhide]
name=Fedora - Rawhide - Developmental packages for the next Fedora release
failovermethod=priority
#baseurl=http://download.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/$basearch/os/
baseurl=https://mirrors.kernel.org/fedora/development/rawhide/Everything/$basearch/os/
#metalink=https://mirrors.fedoraproject.org/metalink?repo=rawhide&arch=$basearch
enabled=1
metadata_expire=6h
repo_gpgcheck=0
type=rpm
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False
```

**Comment by shrisha108** [comment]
Oh! thank you! yes, installing now.

**Comment by shrisha108** [comment]
Installed only with one error in Deepin terminal. But unfortunately when I'm trying to login in deepin from GDM it's just blink for 1 second with black screen and goes back to GDM.

**Comment by 1dot75cm** [comment]
What's wrong with the system log? @shrishadas
```
# journalctl -e
```

**Comment by shrisha108** [comment]
ok, this what I getting:
Nov 30 12:48:32 localhost.localdomain systemd-logind[1081]: Session c2 logged out. Waiting for processes to exit.
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: Application 'org.gnome.SettingsDaemon.Mouse.desktop' killed by signal 15
Nov 30 12:48:32 localhost.localdomain gsd-color[5275]: failed to connect to device: Failed to connect to missing device /org/freedesktop/ColorManager/devices/xrandr_Samsung_Electric_Company_SAMSUNG_1_gdm_42
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: Application 'org.gnome.SettingsDaemon.PrintNotifications.desktop' killed by signal 15
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: Unrecoverable failure in required component org.gnome.Shell.desktop
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: Application 'org.gnome.SettingsDaemon.Rfkill.desktop' killed by signal 15
Nov 30 12:48:32 localhost.localdomain systemd-logind[1081]: Removed session c2.
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: Application 'org.gnome.SettingsDaemon.ScreensaverProxy.desktop' killed by signal 15
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: Application 'org.gnome.SettingsDaemon.Sharing.desktop' killed by signal 15
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: Application 'org.gnome.SettingsDaemon.A11ySettings.desktop' killed by signal 15
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: Application 'org.gnome.SettingsDaemon.Smartcard.desktop' killed by signal 15
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: Application 'org.gnome.SettingsDaemon.Datetime.desktop' killed by signal 15
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: Application 'org.gnome.SettingsDaemon.Sound.desktop' killed by signal 15
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: Application 'org.gnome.SettingsDaemon.Clipboard.desktop' killed by signal 15
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: Application 'org.gnome.SettingsDaemon.MediaKeys.desktop' killed by signal 15
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: Application 'org.gnome.SettingsDaemon.Keyboard.desktop' killed by signal 15
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: Application 'org.gnome.SettingsDaemon.Wacom.desktop' killed by signal 15
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: Application 'org.gnome.SettingsDaemon.Power.desktop' killed by signal 15
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: Application 'org.gnome.SettingsDaemon.XSettings.desktop' killed by signal 15
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: Application 'org.gnome.SettingsDaemon.Color.desktop' killed by signal 15
Nov 30 12:48:32 localhost.localdomain gnome-session-binary[4218]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1
Nov 30 12:48:32 localhost.localdomain polkitd[1082]: Unregistered Authentication Agent for unix-session:c2 (system bus name :1.568, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Nov 30 12:48:32 localhost.localdomain gdm[1580]: Child process -4209 was already dead.

**Comment by alick** [comment]
这个issue什么时候关闭？什么条件？

**Comment by shrisha108** [comment]
I did fresh Fedora installation and Deepin is installed with now problem. But desktop scaling to 1.5 is not working. That only why I was need Deepin for. Is there any chance to fix it? It's working perfectly in official Deepin distro.

**Comment by sztsian** [comment]
@1dot75cm can you take a look at the aforementioned problem?

**Comment by Quanyu-Mars** [comment]
@y010204025 网易云在copr中有人作了,这个应该是 @1dot75cm 大神打的包 
dnf copr enable mosquito/netease-cloud-music

**Comment by sztsian** [comment]
这个线索与网易云音乐无关。请不要在这儿讨论网易云音乐（如有必要可以去 https://github.com/FZUG/repo 讨论）。

**Comment by sztsian** [comment]
Now we have the self-contained change sent out and approved, and also an ISO for testing, so I am closing this.
