### ISSUE TITLE
can't install deepin-terminal in Fedora 29

### ISSUE THREAD

**Issue by Quanyu-Mars** [FZUG/deepin-desktop#10]
现在，deepin-terminal已进入f29的官方库了，但用dnf 安装deepin-desktop,有依赖依然没有解决。
问题: package deepin-terminal-3.0.3-1.fc29.x86_64 requires deepin-menu, but none of the providers can be installed
  - conflicting requests
  - nothing provides libdframeworkdbus.so.1()(64bit) needed by deepin-menu-3.2.0-3.fc29.x86_64

**Comment by alick** [comment]
Deepin 桌面将会正式登陆 Fedora 30，即下一个版本。开发者精力有限，目前无法保证 Fedora 29 中可用。

**Comment by sztsian** [comment]
Hi，
Fedora 29 官方源中一直没有完成完整的 Deepin 桌面。请耐心等待 Fedora 30。
