### ISSUE TITLE
Inspect why two no-deepin specs in this repo

### ISSUE THREAD

**Issue by sztsian** [FZUG/deepin-desktop#14]
As in https://github.com/FZUG/deepin-desktop/pull/13
The following spec files are deleted
rpms/perl-xml-libxml-prettyprint.spec
rpms/python2-ass.spec

But I think we need to inspect why they were there after the split of repo. If this is for some dependency, then we might need to add them back. Otherwise, adding them back to the https://github.com/FZUG/repo

**Comment by felixonmars** [comment]
IIRC perl-xml-libxml-prettyprint was a dependency of deepin-gettext-tools and python2-ass was a dependency of deepin-movie, both are long gone.

**Comment by alick** [comment]
Closing assuming @felixonmars is right
