### ISSUE TITLE
Installing deepin from latest netinst.iso,  bright white screen

### ISSUE THREAD

**Issue by dance707** [FZUG/deepin-desktop#23]
Installing deepin using Fedora netinst-x86_64-30-20190312.n.0.iso and selecting Base Environment Deepin Desktop. Boots up to a bright white screen. Open tty and install lightdm-gtk and then boots okay  to login screen.

**Comment by cheese** [comment]
Please choose `Deepin Desktop` on the left side.

![Screenshot_fedora30-test-install_2019-03-08_10:02:41](https://user-images.githubusercontent.com/303331/54246791-50c1a600-4571-11e9-9807-dc077ba1a3f9.png)

**Comment by dance707** [comment]
Did you read the full issue before you close this ?  When you do a net install and choose Deepin Desktop on the left side . It will install and then boot to a white screen. I open tty and install lightdm-gtk then it will show a login screen when I boot up.

**Comment by cheese** [comment]
Sorry. I mistook your words. I will have 20190312 a try. I tested 20190301 which installed smoothly.

**Comment by dance707** [comment]
Just trying to help here. I have 3 fedora deepins.  all failed.  2 of them using server-netinst-x86_64-30-20190312.n.0.iso and 1 using workstation-netinst-x86_64-30-20190312.n.0.iso  doing clean install of deepin only
Your previous install's may have had elementary-greeter,  so lightdm-gtk was not needed then.

**Comment by cheese** [comment]
I can't reproduce this situation. Which version of deepin-session-ui is installed after your installation?

It should be 4.8.11-2.fc30. Then lightdm-gtk and elementary-greeter both are not needed. deepin-session-ui provides a deepin-based greeter itself.

**Comment by dance707** [comment]
Here it consistently reproduces the problem. I have older equipment though, this does not occur on my Arch deepin or my official Debian deepin. 
![Webcam-1552478981](https://user-images.githubusercontent.com/11428397/54279311-5eb7fc80-455a-11e9-83c1-31c6ba945181.png)

Yes deepin-session-ui is 4.8.11-2.fc30 and it does throw 2 qt errors on a dnf update
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 qt5-qtbase-gui         x86_64    5.12.1-2.fc30    updates-testing    5.7 M
Skipping packages with broken dependencies:
 deepin-file-manager    x86_64    4.7.7-2.fc30     updates-testing    3.2 M

Transaction Summary
============================================================================

**Comment by cheese** [comment]
Is there any coredump of deepin programs? Run 'coredumpctl' to see.

Is the desktop able to log in if using other greeter?

**Comment by dance707** [comment]
No coredumps found.
Other greeter ? I tried sddm windows manager but there is no user name when the log in screen appears. This issue is especially a problem on a wireless install, then have to find an offline fix. Though I am able to work around the problem . I just posted it here in github so maybe it will help others

**Comment by alick** [comment]
Do you have updates-testing repo enabled?

Is it enabled by default? Shouldn't be so on a released Fedora version, but
Fedora 30 is in beta(?) so not sure.

Can you try with updates-testing disabled?

**Comment by dance707** [comment]
updates-testing was enabled by default on the netinst 
I do not see an option to disable updates-testing repo on a network install.

I suppose it might be possible to downgrade updates-testing packages after the first log in . 

I edited this to add that I do remember a few weeks ago that I had a similar issue when I removed elementary-greeter., that also removed a lot of packages. I was rather surprised to see that the deepin desktop network install did Not install elementary-greeter like the rawhide iso had before.

**Comment by dance707** [comment]
Fedora posted this page on their WIKI  It shows a download link for all the other desktops Live ISO
but no deepin on this page.
https://fedoraproject.org/wiki/Test_Results:Fedora_30_Branched_20190312.n.0_Installation?rd=Test_Results:Current_Installation_Test
It also says do not do updates if you going to report a test case.

**Comment by cheese** [comment]
> Fedora posted this page on their WIKI It shows a download link for all the other desktops Live ISO
> but no deepin on this page.
> https://fedoraproject.org/wiki/Test_Results:Fedora_30_Branched_20190312.n.0_Installation?rd=Test_Results:Current_Installation_Test
> It also says do not do updates if you going to report a test case.

Deepin Live ISO is not planed for Fedora 30, may be for Fedora 31.

**Comment by dance707** [comment]
Okay thank you. Users that want to try Deepin desktop will need to do a net install or a manual install.

Personally I do not understand why previous manual installs pulled in elementary-greeter and elementary-wallpapers. I always removed those.

**Comment by cheese** [comment]
> Okay thank you. Users that want to try Deepin desktop will need to do a net install or a manual install.
> 
> Personally I do not understand why previous manual installs pulled in elementary-greeter and elementary-wallpapers. I always removed those.

deepin-session-ui requires lightdm and lightdm requires at least one package that provides `lightdm-greeter`.
With deepin-session-ui >= 4.8.11-2.fc30, deepin-session-ui provides a lightdm-greeter itself.
But with deepin-session-ui < 4.8.11-2.fc30, dnf has to find other package that provides `lightdm-greeter` and occasionally elementary-greeter is chosen to satisfy this requirement. So if you have deepin-session-ui >= 4.8.11-2.fc30, elementary-greeter can be deleted.

**Comment by dance707** [comment]
The latest net install   server-netinst-x86_64-30-20190316n.1 
works good here for deepin

**Comment by k-caps** [comment]
Happening again on `Fedora-Everything-netinst-x86_64-33-1.2.iso`
