### ISSUE TITLE
error on Fedora 30.

### ISSUE THREAD

**Issue by Quanyu-Mars** [FZUG/deepin-desktop#25]
I install deepin-desktop on fedora 30. 
I can't see anything except the backgroud picture when logining by using Deepin-Desktop.  I can press ctrl+t to launch deepin-terminal normlly.

Could you help me. Thanks.

**Comment by cheese** [comment]
Have you update all packages to latest version? Is this issue appear on every log-in? After the issue appear, change to a terminal and run
```
journalctl -b > log
fpaste log
``
And then paste the fpaste URL here.

**Comment by cheese** [comment]
We have different communication methods other than on Github. We have telegram group and wechat group. You can send a private email to me and I tell you how to join.

**Comment by Quanyu-Mars** [comment]
@cheese 
yes, All packages is latest version, and the issue appears on every deepin log-in.
[This is Log](https://paste.fedoraproject.org/paste/C-aYs-H2XEWINc12vnQ4Tg)

**Comment by Quanyu-Mars** [comment]
ok, the problem has been solved. It's my fault in display setting.
the work of deepin-dekstop for fedora is great.
thanks.
