### ISSUE TITLE
Fresh Fedora 30 installation error (Nvidia specific)

### ISSUE THREAD

**Issue by Saladin1812** [FZUG/deepin-desktop#26]
After fresh fedora 30 install of fedora gnome. I tried deepin DE using exact commands listed here
 https://bbs.deepin.org/forum.php?mod=viewthread&tid=134393&extra=
I ended up in blackscreen lightdm didnt work, I then switched back to Gdm to my gnome User interface. I also tried deepin DE in gdm by simply selecting deepin from gnome login session still black screen.

**Comment by dance707** [comment]
Those instructions on that deepin forum thread where for fc28-29 and alpha 30, are out of date and no longer apply.  If you have a fresh fedora 30 install the easiest way to install deepin desktop is :
sudo dnf groupinstall "Deepin Desktop"

**Comment by Saladin1812** [comment]
will i have to set lightdm or something ? or just the groupinstall will do ?

**Comment by dance707** [comment]
It will work with the gnome display manager. You may also use systemctl commands to change it to lightdm if you prefer.

**Comment by Saladin1812** [comment]
Not working it just shows the mouse. Tested on 2 systems one with nvidia drivers other with integrated intel.

**Comment by Saladin1812** [comment]
Both have freshly installed fedora 30 It just shows the mouse and background. Stuck for half an hour.

**Comment by Saladin1812** [comment]
And on lightdm still total black screen.

**Comment by Saladin1812** [comment]
Should i disable SELinux ?

**Comment by Saladin1812** [comment]
I tried everything its not working on any of my systems confirm this bug.

**Comment by dance707** [comment]
My only other suggestion is to open a tty if you can and do a system update as Fedora released mesa updates after the fc30  ISO was released. The updates fixed black screen with SDDM display manager. I was not aware of any trouble with lightdm or gdm.
![DeepinScreenshot_select-area_20190501154609](https://user-images.githubusercontent.com/11428397/57009297-514cf380-6c28-11e9-8783-3c7de1e2f733.png)

**Comment by Saladin1812** [comment]
Yes i just got updates let me check now I will switch SDDM if didnt work.. Lets see

**Comment by Saladin1812** [comment]
Still the same I dont think it supports Nvidia. Its not working with nvidia drivers.

**Comment by Saladin1812** [comment]
Anyone in your team who has nvidia drivers and fedora 30 ? to help fix this bug.

**Comment by alick** [comment]
It's likely to be an NVIDIA graphic driver issue, which is not DE specific (i.e. it would fail also on GNOME etc.) Hence, I'm going to close this issue. If you confirm it is Deepin specific, you may want to report a bug to the Deepin upstream.

Try installing the proprietary NVIDIA driver and see if it works. If not, then please report bug to NVIDIA. If it works, then consider reporting a bug to the free nouveau driver.

It would help a lot if you can provide your NVIDIA graphic card model/chipset info. (`lspci | grep graph`)

**Comment by Saladin1812** [comment]
No its a deepin DE problem gnome, KDE, cinnamon all work by simply selecting them in gdm and I am using nvidia propreitary drivers its the problem with deepin DE. It seems they only test things on intel and push it. i dont think deepin DE tests itself on AMD and nvidia graphic cards.
