### ISSUE TITLE
Seems to be working on Fedora 29 without disabling SELinux

### ISSUE THREAD

**Issue by EmreAtes** [FZUG/deepin-desktop#3]
In the README there's a line which disables SELinux:
`sudo sed -i "/SELINUX=/s|enforcing|disabled|" /etc/selinux/config`
In recent Fedora 29 there aren't any alerts from deepin, so it seems like that line can be removed.

**Comment by sztsian** [comment]
Thanks for the updates.
That line comes a very long time ago. So I will fix it shortly.
In the mean time, please be aware that Deepin Desktop in Fedora 29 might start to fail as Qt has been updated but we haven't got enough time to do corresponding adjustment.

**Comment by alick** [comment]
@sztsian Is it fixed?

**Comment by sztsian** [comment]
Yes. I've fixed the README.md by https://github.com/FZUG/deepin-desktop/commit/d0836ad79ca898407066d08c2bc2e9bd3e53e469
