### ISSUE TITLE
key binding?

### ISSUE THREAD

**Issue by Bergg** [FZUG/deepin-desktop#4]
How to do key binding in deepin, such as modifying the behaviour of CapsLock and adding a Compose key? The keyboard layout doesn't allow it as far as I can see. Thanks.

**Comment by alick** [comment]
This seems to be an upstream issue.

**Comment by alick** [comment]
Please refer to https://wiki.deepin.org/index.php?title=Modify_keyboard_mapping&language=en . If that does not solve your issue, please open a new discussion on https://bbs.deepin.org/
