### ISSUE TITLE
deepin-terminal trying to access data files from the wrong path

### ISSUE THREAD

**Issue by b-man** [FZUG/deepin-desktop#5]
Hello,

The current build appears to be searching for data files in /builddir/build/BUILD/deepin-terminal-3.0.11.1 instead of /usr/share/deepin-terminal. This is causing deepin-terminal to launch without any UI elements.

**Comment by sztsian** [comment]
Thanks. We will be looking into this later on when we have some time. If this happens in the deepin-terminal package in official Fedora repo, I would suggest you to file a bug in bugzilla.redhat.com as well.
