### ISSUE TITLE
dock tray missing

### ISSUE THREAD

**Issue by dance707** [FZUG/deepin-desktop#6]
dock tray/system tray  is missing from the  deepin dock.

**Comment by 1dot75cm** [comment]
The repository is not synchronized. Please update later.

**Comment by dance707** [comment]
deepin dock tray still missing, does not appear on the dock. was ok 2 weeks ago.

**Comment by dance707** [comment]
After this mornings updates: 
Deepin dock tray  is back to normal on the system built from minimal server iso. :)
Deepin dock tray still missing on the system  built with default gnome workstation iso.
Deepin dock tray also works good on another minimal install.
