### ISSUE TITLE
deepin-topbar uninstallable

### ISSUE THREAD

**Issue by dance707** [FZUG/deepin-desktop#7]
After this mornings updates qt5-qtbase was upgraded to 5.11.3-1
Error: 
 Problem: conflicting requests
nothing provides qt5-qtbase(x86-64) = 5.11.2 needed by deepin-topbar-0.5.1-1

**Comment by 1dot75cm** [comment]
Update to 0.6.0: https://koji.fedoraproject.org/koji/taskinfo?taskID=31594322
