### ISSUE TITLE
possible package dependency issues

### ISSUE THREAD

**Issue by deesto** [FZUG/deepin-desktop#9]
Hi,
Lately I have problems using deepin on Fedora 29, and yum/dnf updates have issues completing successfully, because of two deepin packages (dtkwidget and deepin-qt5integration), specifically their dependencies.

yum/dnf update runs result in the following error output:

`Error:
 Problem 1: problem with installed package dtkwidget-2.0.9.9-3.fc29.x86_64
  - cannot install the best update candidate for package dtkwidget-2.0.9.9-3.fc29.x86_64
  - package dtkwidget-2.0.9.10-1.fc29.x86_64 requires qt5-qtbase(x86-64) = 5.11.1, but none of the providers can be installed
  - cannot install the best update candidate for package qt5-qtbase-5.11.3-1.fc29.x86_64
  - cannot install both qt5-qtbase-5.11.1-7.fc29.x86_64 and qt5-qtbase-5.11.3-1.fc29.x86_64
 Problem 2: problem with installed package deepin-qt5integration-0.3.4-2.fc29.x86_64
  - cannot install the best update candidate for package deepin-qt5integration-0.3.4-2.fc29.x86_64
  - package deepin-qt5integration-0.3.7-1.fc29.x86_64 requires libQt5Gui.so.5(Qt_5.11.1_PRIVATE_API)(64bit), but none of the providers can be installed
  - package deepin-qt5integration-0.3.7-1.fc29.x86_64 requires libQt5Widgets.so.5(Qt_5.11.1_PRIVATE_API)(64bit), but none of the providers can be installed
  - package deepin-qt5integration-0.3.7-1.fc29.x86_64 requires libQt5XcbQpa.so.5(Qt_5.11.1_PRIVATE_API)(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package qt5-qtbase-gui-5.11.3-1.fc29.x86_64
  - cannot install both qt5-qtbase-gui-5.11.1-7.fc29.x86_64 and qt5-qtbase-gui-5.11.3-1.fc29.x86_64`

I am using mosquito's Copr repo to pull the latest package updates. Are there any problems with other builds or distributions?

Thank you.

**Comment by dance707** [comment]
No problem here with Deepin on fc30, 
I have two working system running quite well so far, considering it's Rawhide.
Installed Packages
dtkwidget.x86_64                               2.0.9.11-3.fc30                         @rawhide
deepin-qt5integration.x86_64                      0.3.7.1-2.fc30                       @rawhide

**Comment by deesto** [comment]
Great @dance707 , but as you noted, Rawhide (currently Fedora 30) is not a release. I'm surprised the packages work in Rawhide and not in the latest released version.

**Comment by dance707** [comment]
I do not know why your packages are not working in fc29 , I am just replying to your question of other builds or distributions. But i guess you where just referring to fc29
Fedora Engineering and Steering Committee (FESCo) has formally approved of Deepin being offered by Fedora 30. That is why DeepinDE packages are packaged and built in Fedora Rawhide.

**Comment by deesto** [comment]
Understood, but I don't think ensuring the packages work in Rawhide should be much different than the same in the most current and supported stable version, and there seems to be a difference here between the two. Shouldn't they be tested against CURRENT before being released?

I don't mean to be a pain or make this a major issue, but all I did was update my system, and now I can't use deepin.

**Comment by dance707** [comment]
Maybe the developers here can help you with the third party repo in fc29, so you can use your deepin

**Comment by sztsian** [comment]
Hi, thanks for your interests. Also thanks @dance707 for providing the above information.

As we mentioned in the https://github.com/FZUG/deepin-desktop/blob/master/README.md, you still need to use third part repo to make Deepin work in Fedora 29. The reason is not technically, it's because we don't have enough time to take care of two parallel streams when we are still struggling to make it basically work. As for @deesto 's question of testing it in stable before next release, actually from packaging point of view, it should always go to rawhide first, then if it is fine, we can bring them back to stable.

We've already been told that Qt have been updated in Fedora 29 so some of the Deepin related packages start to fail some days ago, but I believe @1dot75cm haven't got enough time to fix his copr yet. I've just reminded him for this.

**Comment by deesto** [comment]
Hi,
> As we mentioned in the https://github.com/FZUG/deepin-desktop/blob/master/README.md, you still need to use third part repo to make Deepin work in Fedora 29. The reason is not technically, it's because we don't have enough time to take care of two parallel streams when we are still struggling to make it basically work. 

That is fine. I am already using the copr repo, as i mentioned.

>As for @deesto 's question of testing it in stable before next release, actually from packaging point of view, it should always go to rawhide first, then if it is fine, we can bring them back to stable.

I have never before heard of prioritizing a future release over the most current and stable one. As you see in this case, this policy resulted in a broken release. 

> We've already been told that Qt have been updated in Fedora 29 so some of the Deepin related packages start to fail some days ago, but I believe @1dot75cm haven't got enough time to fix his copr yet. I've just reminded him for this.

Thank you.

**Comment by sztsian** [comment]
> I have never before heard of prioritizing a future release over the most current and stable one. As you see in this case, this policy resulted in a broken release.

Hi, I don't mean the two are relevant.

The dependency issue is simply caused by our time constraint. We all work on this packaging effort in our spare time, so in many cases we cannot catch up with each of the dependency problems in time. Sorry for the convenience. We will try to catch up with each major changes in Fedora 30, at least as soon as possible

**Comment by unleashedcode** [comment]
I am having the same issue too, pleased to see sztsian is aware and it will be addressed when time is more availble.....

**Comment by sztsian** [comment]
All,
I suggest you to update to Fedora 30 and use the Deepin Desktop related packages from Fedora repo directly. We are lacking of capacity to fix these in Fedora 29 yet but Fedora 30 seems working fare enough (with some minor problems).
If you still have problems with Deepin Desktop on Fedora 30, feel free to report bugs directly on https://bugzilla.redhat.com . 
You can still report bugs here in github issues if you do not have an account on bugzilla (and you do not want to register one).
